name: TruffleHog

on: [push, pull_request]

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch name1
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Branch name2
        run: echo running on branch ${{ github.ref }}
      - name: Branch name3 (source branch in PR)
        run: echo $GITHUB_HEAD_REF
      - name: Branch name4 (target branch in PR)
        run: echo $GITHUB_BASE_REF
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD